---
# tasks file for tmux

- name: Include distribution specific variables
  include_vars: "{{ ansible_distribution }}.yml"
  tags: tmux

- include: CentOS.yml
  when: ansible_distribution == "CentOS"
  tags: tmux

- include: FreeBSD.yml
  when: ansible_distribution == "FreeBSD"
  tags: tmux

- include: Ubuntu.yml
  when: ansible_distribution == "Ubuntu"
  tags: tmux
